### ISSUE TITLE
analyse_freenrg mbar issues with passing lamabda array

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#179]
when calling analyse_freenrg mbar in the following way:
```bash
analyse_freenrg mbar --lam 0.000 0.125 0.250 0.375 0.500 0.625 0.750 0.875 1.000 -i lam*/simfile.dat --temperature 298 -o out.dat -p 90
```
I get this output:
```bash
Simulation data is analysed using the python module pymbar
----------------------------------------------------------
# Writing all output to file out.dat
working on input file lambda-0.0000/simfile.dat
working on input file lambda-0.1250/simfile.dat
working on input file lambda-0.2500/simfile.dat
working on input file lambda-0.3750/simfile.dat
working on input file lambda-0.5000/simfile.dat
working on input file lambda-0.6250/simfile.dat
working on input file lambda-0.7500/simfile.dat
working on input file lambda-0.8750/simfile.dat
working on input file lambda-1.0000/simfile.dat
Traceback (most recent call last):
  File "/home/ppxasjsm/sire.app_dev/pkgs/sire-2017.2.0/share/Sire/scripts/analyse_freenrg.py", line 595, in <module>
    N_k = numpy.zeros(shape=lamvals.shape[0], dtype='int32')
AttributeError: 'list' object has no attribute 'shape'
```

Running without explicit lambda argument works fine.

**Comment by lohedges** [comment]
I think you want to change line 509 in `analyse_freenrg.py` to:

```python
lamvals = numpy.array(args.lam)
```
At the moment it looks like the lambda values are getting stored list.

(I've not tested this since I don't have any input files.)

Cheers.

**Comment by ppxasjsm** [comment]
Yeah the fix is easy and exactly what you say, was just in the middle of something else so wanted to leave a note for myself for later....

**Comment by ppxasjsm** [comment]
fixed with b59ef9b
